Repository apache/uima-ruta, pull requests merged in 2024-11, with the labels that each got.

#174 Issue #173: Potential memory leak in Annotation Browser View
  ruta-ep-caseditor/src/main/java/org/apache/uima/ruta/caseditor/view/tree/AnnotationTreeViewPage.java
Labels: 🦟 Bug

#180 Issue #179: Remove toolchains
  ruta-parent/pom.xml
Labels: refactoring

#181 Issue #176 - Upgrade dependencies
  ruta-parent/pom.xml
Labels: refactoring

#178 Issue #177: Consider resource manager when loading type descriptions
  ruta-core/src/main/java/org/apache/uima/ruta/RutaEnvironment.java
  ruta-core/src/main/java/org/apache/uima/ruta/descriptor/RutaDescriptorBuilder.java
  ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
  ruta-core/src/main/java/org/apache/uima/ruta/resource/RutaResourceLoader.java
  ruta-core/src/main/java/org/apache/uima/ruta/type/spi/RutaBasicTypeProvider.java
  ruta-core/src/main/java/org/apache/uima/ruta/type/spi/RutaTypeSystemDescriptionProvider.java
  ruta-core/src/main/resources/META-INF/services/org.apache.uima.spi.JCasClassProvider
  ruta-core/src/main/resources/META-INF/services/org.apache.uima.spi.TypeSystemDescriptionProvider
  ruta-parent/pom.xml
Labels: ⭐️ Enhancement

#182 Issue #176: Upgrade dependencies
  pom.xml
  ruta-core/pom.xml
  ruta-documentation/pom.xml
  ruta-ep-engine/src/main/readme_bin/LICENSE
  ruta-ep-engine/src/main/readme_bin/NOTICE
  ruta-ep-ide/pom.xml
  ruta-maven-archetype/pom.xml
  ruta-parent/pom.xml
Labels: refactoring

#186 Issue #176: Upgrade dependencies
  ruta-eclipse-feature/feature.xml
Labels: refactoring

#187 Issue #177: Consider resource manager when loading type descriptions
  ruta-core/pom.xml
  ruta-core/src/main/java/org/apache/uima/ruta/type/spi/RutaTypeSystemProvider.java
  ruta-core/src/main/resources/META-INF/services/org.apache.uima.spi.TypeSystemProvider
Labels: ⭐️ Enhancement
